[package]
name = "caffpay_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.12"
ic-cdk-macros = "0.7"
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
once_cell = "1.19"
